### ISSUE TITLE
Eternal loading

### ISSUE THREAD

**Issue by Daniel-Mietchen** [hay/wiki-tools#68] opened 2020-08-29 08:37 UTC
This is what I've been seeing most of the time for the past few weeks. Did occasionally see it work properly in between, so thought somebody was keeping an eye on it. In any case, I don't see an issue for it here, so opening one now.

![Screenshot_2020-08-29 Wikidata Propbrowse - Hay's tools](https://user-images.githubusercontent.com/465923/91632755-f4468680-e9b0-11ea-9a9a-461897969cb3.png)

**Comment by hay** [comment] 2020-08-29 15:52
Hey Daniel, thanks for reporting this. It's a bit weird, the screenshots seems to show a state of the tool where no CSS or Javascript is loaded, but i have no issues with the current tools. I checked in a couple of browsers, but all seems to work fine. Maybe you could let me know:

* OS
* Browser and browser version
* If you're using any kind of extensions or ad blockers?
* If you just have this with Propbrowse or the others tools as well? If so, let me know which ones. 

So i can see if i can reproduce the issue.

**Comment by Daniel-Mietchen** [comment] 2020-08-30 10:03
I am using Firefox 79.0 under OSX 10.15.6, with add-ons as per the attached screenshot. Propbrowse is the only tool for which I noticed these problems.
<img width="686" alt="Screen Shot 2020-08-30 at 06 01 50" src="https://user-images.githubusercontent.com/465923/91656386-591fe080-ea86-11ea-87e2-fe3b71cc075f.png">

**Comment by hay** [comment] 2020-08-30 15:14
Thanks for posting your configuration. I'm using Firefox 80 on OSX 10.14, and i also tried loading Propbrowse while using Privacy Badger and Entity Explosion, but i can't replicate this problem. Have you tried doing a hard refesh on the Propbrowse page by using Shift+Command+R?

**Comment by Daniel-Mietchen** [comment] 2020-09-02 02:42
Yes, I tried Shift+Command+R, and it does not change the situation. Can confirm Propbrowse works under Chrome on the same system.

**Comment by hay** [comment] 2020-09-02 09:05
Okay, i'm afraid i need to close this ticket because i think we've ran out of options. I'm not quite sure how to reproduce the problem, and i don't think there is any difference in how Firefox would handle rendering Propbrowse than Chrome. Hopefully the problem will solve itself when your Firefox gets updated.

**Closed by hay** 2020-09-02 09:05 UTC

**Comment by Daniel-Mietchen** [comment] 2020-09-23 02:31
I still had the problem with Firefox 80 and now, after just upgrading to 81, it is still there, despite browser restarts and cache resets.

**Comment by hay** [comment] 2020-09-23 12:04
:(
